<h2>Help me!</h2>
<dl>
    <dt>I'm a hermit web programmer, how do I get girls?!</dt>
    <dd>Go to the bar and talk to people.</dd>

    <dt>I talked to a girl and I think it may have been awkward.</dt>
    <dd>Keep trying. Don't talk about computers, they'll either blow you off
        or ask you to help install their printer.</dd>

    <dt>I couldn't help but talk about computers: She gave me her number and 
        didn't ask me to help her with computer problems.</dt>
    <dd>Keeper.</dd>
</dl>